# fly.toml app configuration file generated for scala-api on 2023-07-15T11:24:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scala-api"
primary_region = "lhr"


[services]
  [services.http]
    ports = ["8080"]
    handlers = ["fly.http.platform"]
    [[services.http.checks]]
      type = "http"
      port = "8080"